[features]
seeds = false
skip-lint = false
[programs.localnet]
storylands = "2gYJ5iXaV5R8VisVa5iHcK1aijqZq13BkViCKjGecdyd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bradleythompson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
dev-app = "yarn --cwd ./app/storylands dev"
local = "solana-test-validator"
