[features]
seeds = false
skip-lint = false
[programs.localnet]
storylands = "9xDxgwW2LCPBWVrDc5Wucim953CcNzjh7KjPupuq9Vm"

[workspace]
types = "app/storylands/src/idl/"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bradleythompson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
dev-app = "yarn --cwd ./app/storylands dev"